export default {
    LOAD_DATALIST: 'LOAD_DATALIST',
    LOAD_DETAILED_DATA: 'LOAD_DETAILED_DATA',
    CONNNECT_NEW_USER: 'CONNECT_NEW_USER',
    SEND_NEW_MESSAGE: 'SEND_NEW_MESSAGE',
    GET_MESSAGES: 'GET_MESSAGES',
    CHANGE_USERNAME: 'CHANGE_USERNAME',
    DISCONNNECT_USER: 'DISCONNECT_USER',
    GET_USERS: 'GET_USERS'
};
