export default {
    CONNNECT_NEW_USER: 'CONNECT_NEW_USER',
    SEND_NEW_MESSAGE: 'SEND_NEW_MESSAGE',
    GET_MESSAGES: 'GET_MESSAGES',
    CHANGE_USERNAME: 'CHANGE_USERNAME',
    DISCONNNECT_USER: 'DISCONNECT_USER',
    GET_USERS: 'GET_USERS'
};
